spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_prod
    username: blog_prod_user
    password: intec
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false